
version: '2'

services:
  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: local
      MYSQL_DATABASE: local
      MYSQL_USER: local
      MYSQL_PASSWORD: local
    networks:
      default:

  web:
    image: uofa/apache2-php7-dev
    volumes:
      - .:/web
    environment:
      - VIRTUAL_HOST=${PROJECT}.${DOMAIN}
    networks:
      default:

  mail:
    image: helder/mailcatcher
    environment:
      - VIRTUAL_HOST=mail.${PROJECT}.${DOMAIN}
    networks:
      default:
